name: Check Links
on: workflow_dispatch

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#      with:
#        ref: gh-pages
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
#        use-verbose-mode: 'yes'
#        config-file: 'mlc_config.json'
        folder-path: 'docs'
	baseUrl: 'https://ringcentral.github.io/ringcentral-api-docs/'
